---
- name: Install python3  and docker
  hosts: docker_server
  become: yes
  # become_user: root by default root
  # disable the gather facts task 
  gather_facts: False
  tasks:
    - name: Install python3 ,docker and docker-compose
      vars:
        ansible_python_interpreter: /usr/bin/python
      yum:
        name:
        - python3
        - docker
        update_cache: yes
        state: present

    - name: Install docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.27.4/docker-compose-Linux-{{lookup('pipe','uname -m')}}
        dest: /usr/local/bin/docker-compose
        mode: +x
    - name: start docker daemon 
      systemd:
        name: docker
        state: started
    - name: Install  docker and docker-compose python modules 
      pip:
        name: 
          - docker
          - docker-compose


# docker-compose is not a yum package 
# - name: Install docker-compose
#   hosts: docker_server
#   become: yes
#   tasks:
#   - name: Install docker-compose
#     get_url:
#       url: https://github.com/docker/compose/releases/download/1.27.4/docker-compose-Linux-{{lookup('pipe','uname -m')}}
#       dest: /usr/local/bin/docker-compose
#       mode: +x


# - name: Start docker
#   hosts: docker_server
#   become: yes
#   tasks:
#   - name: start docker daemon 
#     systemd:
#       name: docker
#       state: started

- name: Create new linux user
  hosts: docker_server
  become: yes
  tasks:
    - name: Create new linux user
      user:
        name: Oussama
        groups: adm,docker
# - name: Test docker pull
#   hosts: docker_server
#   tasks:
#     - name: Pull redis
#       # command: docker pull redis
#       docker_image:
#         name: redis
#         source: pull

- name: Starting docker containers
  hosts: docker_server
  become: yes
  become_user: Oussama
  vars_files:
    - project-vars
  # vars_prompt:
  #   - name: docker_password
  #     prompt: Enter password for docker registry
  # we can store the value in vars_files
  tasks:
    - name: Copy Docker Compose 
      copy:
        src: ./docker-compose.yml
        dest: /home/Oussama/docker-compose.yml
    # we need to login first to docker hub registry
    - name: Docker login
      docker_login:
        registry_url: https://index.docker.io/v1/ # by default the value is docker hub we don't need to specifie that
        username: oussamamaaroufi1
        password: "{{docker_password}}"
    - name: Start Container from compose 
      docker_compose:
        project_src: /home/Oussama
        state: present # docker-compose up   









