---
- name: Configure nginx webserver
  hosts: 34.219.96.214
  tasks:
  - name: install nginx server
    apt: 
      name: nginx
      state: present
    # become: yes
    
  - name: start nginx server
    service:
      name: nginx
      state: started
    # become: yes
    